//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_BTL_VERSION_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentDetail = new HashSet<StudentDetail>();
        }
    
        public int StudentID { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string StudentCode { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string Course { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [RegularExpression(@"[0-9]{8}@vnu.edu.vn", ErrorMessage = "Email phải có dạng xxxxxxxx@vnu.edu.vn với x là số")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string PassWord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDetail> StudentDetail { get; set; }
    }
}
