//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_BTL_VERSION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int SurveyID { get; set; }
        public Nullable<int> StudentDetailID { get; set; }
        public Nullable<int> ContentSurveyID { get; set; }
        public Nullable<double> Point { get; set; }
    
        public virtual ContentSurvey ContentSurvey { get; set; }
        public virtual StudentDetail StudentDetail { get; set; }
    }
}
