//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UET_BTL_VERSION_1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.StudentDetail = new HashSet<StudentDetail>();
        }
    
        public int TeacherID { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string Name { get; set; }
        public string TeacherCode { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [RegularExpression(@"[a-z]{4,10}@vnu.edu.vn", ErrorMessage = "Email phải có dạng x@vnu.edu.vn với x từ 4 đến 10 các chữ cái")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string PassWord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDetail> StudentDetail { get; set; }
    }
}
