//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.ThamGia = new HashSet<ThamGia>();
        }
       
        [Display(Name = "Mã sách")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public int MaSach { get; set; }
        [Display(Name = "Tên sách")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string TenSach { get; set; }
        [Display(Name = "Gía bán")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public Nullable<decimal> GiaBan { get; set; }
        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public string MoTa { get; set; }
        [Display(Name = "Ngày cập nhật")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [Display(Name = "ảnh bìa")]
        public string AnhBia { get; set; }
        [Display(Name = "Số lượng tồn")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public Nullable<int> SoLuongTon { get; set; }
        [Display(Name = "Mã chủ đề")]
        public Nullable<int> MaChuDe { get; set; }
        [Display(Name = "Mã nhà xuất bản")]
        public Nullable<int> MaNXB { get; set; }
        [Display(Name = "Mới")]
        [Required(ErrorMessage = "{0} không được để trống")]
        public Nullable<int> Moi { get; set; }
        [Display(Name = "Chủ đề")]
        public virtual ChuDe ChuDe { get; set; }
        [Display(Name = "Nhà xuất bản")]
        public virtual NhaXuatBan NhaXuatBan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGia> ThamGia { get; set; }
    }
}
